@extends('layouts.app')
@section('title','Agregar al pedido #'.$order->id.' | Mekatos')
@section('content')
<div class="page-shell">
<div class="page-heading"><div><span class="eyebrow">Adición de pedido</span><h2>Agregar al pedido #{{ $order->id }}</h2><p>Agrega productos nuevos sin crear otra cuenta.</p></div><a class="button" href="{{ route('waiter.orders') }}">Volver</a></div>
@if($errors->any())<div class="alert alert-error"><strong>Revisa la adición.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.orders.add.store',$order) }}" id="addition-form">@csrf
<section class="panel step"><div class="panel-header"><h3>Pedido actual</h3><span>#{{ $order->id }}</span></div>
<div class="order-context"><strong>{{ $order->type?->value === 'MESA' ? '🪑 Mesa '.($order->tableSession?->restaurantTable?->number ?? '—') : ($order->type?->value === 'DOMICILIO' ? '🛵 Domicilio' : '🥡 Para llevar') }}</strong><span>Total actual: &#36;{{ number_format($order->total,0,',','.') }}</span></div>
</section>
<section class="panel step"><div class="panel-header"><h3>1. Productos nuevos</h3><span id="items-count">0 productos seleccionados</span></div>
<div class="tools"><input id="product-search" type="search" placeholder="Buscar producto..."><select id="category-filter"><option value="">Todas las categorías</option>@foreach($categories as $category)<option value="{{$category->id}}">{{$category->name}}</option>@endforeach</select></div>
<div class="grid" id="product-grid">
@foreach($products as $product)
@php $qty=(int)old('items.'.$product->id,0);$isJuice=$product->name==='Jugo Natural Jarra';$isHamburger=$product->category?->name==='Hamburguesas';$options=$product->beverageOptions;@endphp
<article class="card" data-name="{{strtolower($product->name)}}" data-category="{{$product->category_id}}" data-packaging="{{\App\Support\TakeawayPackaging::applies($product)?'1':'0'}}">
<span class="eyebrow">{{$product->category?->name}}</span><h3>{{$product->name}}</h3><p>{{$product->description}}</p>
<div class="bottom"><strong>&#36;{{number_format($isJuice?8500:$product->price,0,',','.')}}</strong><div class="qty"><button type="button" data-minus="{{$product->id}}">−</button><input name="items[{{$product->id}}]" value="{{$qty}}" min="0" max="99" data-id="{{$product->id}}" data-price="{{$product->price}}" data-juice="{$isJuice?'1':'0'}}" readonly><button type="button" data-plus="{{$product->id}}">+</button></div></div>
@if($isHamburger)<div class="options combo"><label>¿Desea combo?<select class="combo-choice" name="combo[{{$product->id}}]" data-id="{{$product->id}}"><option value="NO">No</option><option value="SI">Sé .·T$4.000</option></select></label><div class="combo-extra" data-combo-extra="{{$product->id}}" hidden><label>Bebida1select name="combo_beverage_type[{{$product->id}}]" data-combo-type="{{$product->id}}">@foreach($comboBeverages as $type=>$data)<option value="{{$type}}">{{$data['label']}}</option>@endforeach</select></label><label>Sabor<select name="combo_beverage_flavor[{{$product->id}}]" data-combo-flavor="{{$product->id}}">@foreach(($comboBeverages[array_key(comboBeverages)]['flavors'] ?? []) as $flavor)<option value="{{$flavor}}">{{$flavor}}</option>@endforeach></select></label></div></div>
@elseif($isJuice)><div class="options juice"><label>Preparación<select name="juice_preparation[{{$product->id}}]"><option value="AGUA">En agua</option><option value="LECHE">En leche</option></select></label><label>Fruta<select name="juice_fruit{{$product->id}}]">@foreach(['MARACUYA'=>'Maracuyá','LULO'=>'Lulo','MORA'=>'Mora','FRESA'=>'Fresa','OTRO'=>'Otro'] as $v=>$l)><option value="{{$v}}">{{$l}}</option>@endforeach</select></label></div>
@elseif($options->count())<div class="options beverage" data-options="{{$product->id}}" hidden><label>Opción<offsetselect name="beverage_option{{$product->id}}]"><option value="">Selecciona una opciónax</option>@foreach($options as $option)<option value="{{$option->name}}">{{$option->name}}</option>@endforeach</select></label></div>@endif
<div class="note" hidden><textarea name="item_notes[{{$product->id}}]" maxlength="500" placeholder="Detalle: sin cebolla, extra queso...">{{old('item_notes.'.$product->id)}}</textarea></div>
</article>
@endforeach
</div><div id="products-empty" class="empty-state" hidden>No encontramos productos.</div></section>
<section class="panel step"><div class="panel-header"><h3>2. Revisar y agregar</h3></div><div id="summary" class="summary">Agrega productos para ver el resumen.</div><div class="form-actions"><a class="button" href="{{ route('waiter.orders') }}">Cancelar</a><button class="button button-primary" id="submit" type="submit" disabled>Agregar al pedido</button></div></section>
</form></div>
<style>
.step{margin-bottom:20px}.panel-header{display:flex;justify-content:space-between}.order-context{display:flex;justify-content:space-between;gap:12px;margin:0 22px 18px;padding:14px;border:1px solid #e2d5ae;border-radius:10px;background:#fffdf7}.order-context span{color:#6f6254}.tools{display:flex;gap:8px;padding:0 22px 18px}.tools input,.tools select{padding:10px;border:1px solid #d7c89e;border-radius:8px;background:#fffdf7}.tools input{flex:1}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:0 22px 22px}.card{padding:15px;border:1px solid #e2d5ae;border-radius:12px;background:#fffdf7}.card[hidden]{display:none!important}.card.selected{border-color:#777;box-shadow:0 7px 20px rgba(0,0,0,.07)}.card h3{margin:5px 0}.card p{font-size:.8rem;color:#6f6254;min-height:32px}.bottom{display:flex;justify-content:space-between;align-items:center;gap:8px}.qty{display:flex;border:1px solid #d7c89e;border-radius:8px;overflow:hidden}.qty button{width:32px;border:0;background:#f6ecd0;font-size:18px}.qty input{width:38px;border:0;text-align:center;background:#fff}.options{margin-top:12px;padding:10px;background:#f7f7f5;border-radius:8px}.options[hidden],.note[hidden]{display:none}.options label{font-size:.72rem;font-weight:750}.note{margin-top:10px}.note textarea{width:100%;min-height:50px;border:1px solid #d7c89e;border-radius:8px;padding:7px}.summary{margin:0 22px 20px;padding:14px;background:#f8e7ae;border-radius:10px}.summary-line{display:flex;justify-content:space-between;padding:5px 0;gap:12px}.summary-line small{display:block;color:#6f6254}.summary-fee{border-top:1px dashed #cbbd95;margin-top:8px;padding-top:8px}.form-actions{margin:0 22px}.form-actions .button{margin-right:6px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid{grid-template-columns:1fr}.tools{flex-direction:column}.form-actions{display:grid;grid-template-columns:1fr 1.3fr}.form-actions .button{margin:0}}
</style>
<script>
const submit=document.getElementById('submit'),summary=document.getElementById('summary'),search=document.getElementById('product-search'),filter=document.getElementById('category-filter');
const type='{{ $order->type?->value }}',takeaway=type==='PARA_LLEVAR',delivery=type==='DOMICILIO',comboBeverages=@json($comboBeverages);
const money=v=>'$'+Number(v).toLocaleString('es-CO',{maximumFractionDigits:0});
function applyFilters(){const q=search.value.trim().toLowerCase(),cat=filter.value;let n=0;document.querySelectorAll('.card').forEach(c=>{const ok=(!q||(c.dataset.name||'').includes(q)||(c.querySelector('.eyebrow')?.textContent||'').toLowerCase().includes(q))&&(!cat||c.dataset.category===cat);c.hidden=!ok;if(ok)n++;});document.getElementById('products-empty').hidden=n>0;}
function refresh(){let total=0,units=0,packaging=0,lines=[];document.querySelectorAll('.card').forEach(c=>{const i=c.querySelector('input[data-id]'),q=Number(i.value)||0;c.classList.toggle('selected',q>0);const note=c.querySelector('.note'),bev=c.querySelector('.beverage'),combo=c.querySelector('.combo-choice'),extra=c.querySelector('.combo-extra');if(note)note.hidden=q===0;if(bev)btry{} catch(e){}