@extends('layouts.app')
@section('title','Nuevo pedido | Mekatos')
@section('content')
<div class="page-shell"><div class="page-heading"><div><span class="eyebrow">Operación</span><h2>Nuevo pedido</h2><p>Arma el pedido desde caja o desde el panel del mesero.</p></div><a class="button" href="{{ auth()->user()?->role?->value === 'MESERO' ? route('waiter.orders') : route('admin.orders.index') }}">Volver</a></div>
@if($errors->any())<div class="alert alert-error"><strong>Revisa el pedido.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.orders.store') }}" id="manual-order-form">@csrf
<section class="panel step"><div class="panel-header"><h3>1. Tipo de pedido</h3></div><div class="types"><label><input type="radio" name="type" value="MESA" {{old('type','MESA')==='MESA'?'checked':''}}> 🪑 En mesa</label><label><input type="radio" name="type" value="PARA_LLEVAR" {{old('type')==='PARA_LLEVAR'?'checked':''}}> 🥡 Para llevar</label></div><div id="table-field"><label>Mesa<select name="table_id"><option value="">Selecciona una mesa</option>@foreach($tables as $table)<option value="{{$table->id}}" {{(string)old('table_id')===(string)$table->id?'selected':''}}>Mesa {{$table->number}}{{$table->name?' · '.$table->name:''}}</option>@endforeach</select></label></div></section>
<section class="panel step"><div class="panel-header"><h3>2. Productos</h3><span id="items-count">0 productos seleccionados</span></div><div class="tools"><input id="product-search" type="search" placeholder="Buscar producto..."><select id="category-filter"><option value="">Todas las categorías</option>@foreach($categories as $category)<option value="{{$category->id}}">{{$category->name}}</option>@endforeach</select></div><div class="grid" id="product-grid">
@foreach($products as $product)@php $qty=(int)old('items.'.$product->id,0);$isJuice=$product->name==='Jugo Natural Jarra';$options=$product->beverageOptions;@endphp
<article class="card {{$qty?'selected':''}}" data-name="{{strtolower($product->name)}}" data-category="{{$product->category_id}}"><span class="eyebrow">{{$product->category?->name}}</span><h3>{{$product->name}}</h3><p>{{$product->description}}</p><div class="bottom"><strong>${{number_format($isJuice?8500:$product->price,0,',','.')}}</strong><div class="qty"><button type="button" data-minus="{{$product->id}}">−</button><input name="items[{{$product->id}}]" value="{{$qty}}" min="0" max="99" data-id="{{$product->id}}" data-price="{{$product->price}}" data-juice="{{$isJuice?'1':'0'}}" readonly><button type="button" data-plus="{{$product->id}}">+</button></div></div>
@if($isJuice)<div class="options juice"><label>Preparación<select name="juice_preparation[{{$product->id}}]"><option value="AGUA">En agua</option><option value="LECHE">En leche</option></select></label><label>Fruta<select name="juice_fruit[{{$product->id}}]">@foreach(['MARACUYA'=>'Maracuyá','LULO'=>'Lulo','MORA'=>'Mora','FRESA'=>'Fresa','OTRO'=>'Otro'] as $v=>$l)<option value="{{$v}}">{{$l}}</option>@endforeach</select></label></div>@elseif($options->count())<div class="options beverage" data-options="{{$product->id}}" {{$qty?'':'hidden'}}><label>Opción<select name="beverage_option[{{$product->id}}]"><option value="">Selecciona una opción</option>@foreach($options as $option)<option value="{{$option->name}}">{{$option->name}}</option>@endforeach</select></label></div>@endif
<div class="note" {{$qty?'':'hidden'}}><textarea name="item_notes[{{$product->id}}]" maxlength="500" placeholder="Detalle: sin cebolla, extra queso...">{{old('item_notes.'.$product->id)}}</textarea></div></article>@endforeach</div><div id="products-empty" class="empty-state" hidden>No encontramos productos.</div></section>
<section class="panel step"><div class="panel-header"><h3>3. Revisar y crear</h3></div><label>Notas generales<textarea name="notes" rows="3" maxlength="2000">{{old('notes')}}</textarea></label><div id="summary" class="summary"></div><div class="form-actions"><a class="button" href="{{auth()->user()?->role?->value==='MESERO'?route('waiter.orders'):route('admin.orders.index')}}">Cancelar</a><button class="button button-primary" id="submit" type="submit" disabled>Crear pedido</button></div></section></form></div>
<style>.step{margin-bottom:20px}.panel-header{display:flex;justify-content:space-between}.types{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:20px 22px}.types label{padding:14px;border:1px solid #e2d5ae;border-radius:10px}.step>label,.step>#table-field{display:block;margin:0 22px 18px}.step label>select,.step label>textarea,.step>label>textarea{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #d7c89e;border-radius:8px;background:#fffdf7}.tools{display:flex;gap:8px;padding:0 22px 18px}.tools input,.tools select{padding:10px;border:1px solid #d7c89e;border-radius:8px;background:#fffdf7}.tools input{flex:1}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:0 22px 22px}.card{padding:15px;border:1px solid #e2d5ae;border-radius:12px;background:#fffdf7}.card.selected{border-color:#777;box-shadow:0 7px 20px rgba(0,0,0,.07)}.card h3{margin:5px 0}.card p{font-size:.8rem;color:#6f6254;min-height:32px}.bottom{display:flex;justify-content:space-between;align-items:center;gap:8px}.qty{display:flex;border:1px solid #d7c89e;border-radius:8px;overflow:hidden}.qty button{width:32px;border:0;background:#f6ecd0;font-size:18px}.qty input{width:38px;border:0;text-align:center;background:#fff}.options{margin-top:12px;padding:10px;background:#f7f7f5;border-radius:8px}.options[hidden],.note[hidden]{display:none}.options label{font-size:.72rem;font-weight:750}.note{margin-top:10px}.note textarea{width:100%;min-height:50px;border:1px solid #d7c89e;border-radius:8px;padding:7px}.summary{margin:0 22px 20px;padding:14px;background:#f8e7ae;border-radius:10px}.summary-line{display:flex;justify-content:space-between;padding:5px 0}.summary-line small{display:block;color:#6f6254}.empty-state{text-align:center;padding:20px}.form-actions{margin:0 22px}.form-actions .button{margin-right:6px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid,.types{grid-template-columns:1fr}.tools{flex-direction:column}.form-actions{display:grid;grid-template-columns:1fr 1.3fr}.form-actions .button{margin:0}}
</style>
<script>
const form=document.getElementById('manual-order-form'),submit=document.getElementById('submit'),summary=document.getElementById('summary'),search=document.getElementById('product-search'),filter=document.getElementById('category-filter'),tableField=document.getElementById('table-field');const money=v=>'$'+Number(v).toLocaleString('es-CO',{maximumFractionDigits:0});
function refresh(){let total=0,units=0,lines=[];document.querySelectorAll('.card').forEach(c=>{const i=c.querySelector('input[data-id]'),q=Number(i.value)||0;c.classList.toggle('selected',q>0);const n=c.querySelector('.note'),o=c.querySelector('.beverage');if(n)n.hidden=q===0;if(o)o.hidden=q===0;if(q){let price=Number(i.dataset.price),detail='';if(i.dataset.juice==='1'){const prep=c.querySelector('[name^="juice_preparation"]')?.value||'AGUA';price=prep==='LECHE'?9500:8500;const f=c.querySelector('[name^="juice_fruit"]')?.selectedOptions[0]?.text||'';detail=(prep==='LECHE'?'En leche':'En agua')+' · '+f}else{const s=c.querySelector('.beverage select');detail=s?.value||''}total+=q*price;units+=q;lines.push(`<div class="summary-line"><span>${q} × ${i.closest('.card').querySelector('h3').textContent}<small>${detail}</small></span><strong>${money(q*price)}</strong></div>`)}});document.getElementById('items-count').textContent=`${units} producto${units===1?'':'s'} seleccionado${units===1?'':'s'}`;summary.innerHTML=lines.length?lines.join('')+`<div class="summary-line"><strong>Total</strong><strong>${money(total)}</strong></div>`:'Agrega productos para ver el resumen.';submit.disabled=units===0;}
document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const i=document.querySelector(`input[data-id="${b.dataset.plus}"]`);i.value=Math.min(99,Number(i.value)+1);refresh()});document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=document.querySelector(`input[data-id="${b.dataset.minus}"]`);i.value=Math.max(0,Number(i.value)-1);refresh()});document.querySelectorAll('.beverage select,.juice select').forEach(s=>s.addEventListener('change',refresh));document.querySelectorAll('.card .note textarea').forEach(t=>t.addEventListener('input',refresh));document.querySelectorAll('input[name="type"]').forEach(r=>r.addEventListener('change',()=>{tableField.style.display=r.value==='MESA'&&r.checked?'block':'none'}));search.oninput=filter.onchange=()=>{const q=search.value.toLowerCase(),cat=filter.value;let n=0;document.querySelectorAll('.card').forEach(c=>{const v=(!q||c.dataset.name.includes(q))&&(!cat||c.dataset.category===cat);c.hidden=!v;if(v)n++});document.getElementById('products-empty').hidden=n>0};refresh();
</script>
@endsection
